name: Run-Daily

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight every day
    - cron: '*/3 * * * *'  # Runs every 3 minutes

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run Node.js script
        run: node my-cron-job-script.js