name: Generate and Commit Data

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "20.x"

      - name: Install Dependencies
        run: npm install

      - name: Generate Data
        run: node -e "const fs = require('fs'); const { convertAllToNivoFormat } = require('./src/models/randomDataGenerator'); const data = convertAllToNivoFormat(); fs.writeFileSync('data.json', JSON.stringify(data, null, 2));"

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data.json
          git commit -m "Automatically update data" -a || echo "No changes to commit"
          git push
